version: '3.8'

services:
  adornadesign:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: adornadesign
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adornadesign.rule=Host(`adornadesign.art`) || Host(`www.adornadesign.art`)"
      - "traefik.http.routers.adornadesign.entrypoints=web"
      - "traefik.http.services.adornadesign.loadbalancer.server.port=80"

networks:
  web:
    external: true
